# Generated by Django 5.1.2 on 2024-10-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btns',
            options={'verbose_name': 'button content', 'verbose_name_plural': 'button content'},
        ),
    ]
