# Generated by Django 5.1.2 on 2024-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_btns_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image instead of credit card')),
            ],
            options={
                'verbose_name': 'what image',
                'verbose_name_plural': 'what image',
            },
        ),
    ]
